# Dockerfile MySQL personnalisé
FROM ubuntu

LABEL maintainer="BUFFET Antonin et AKPOVI Amen Manassé"

# Variables d'environnement par défaut
ENV MYSQL_ROOT_PASSWORD=rootpass \
    MYSQL_DATABASE=laravel_db \
    MYSQL_USER=laravel \
    MYSQL_PASSWORD=laravelpass \
    DEBIAN_FRONTEND=noninteractive

# Installation de MySQL Server
RUN apt-get update && \
    apt-get install -y gnupg lsb-release wget && \
    wget https://dev.mysql.com/get/mysql-apt-config_0.8.26-1_all.deb && \
    DEBIAN_FRONTEND=noninteractive dpkg -i mysql-apt-config_0.8.26-1_all.deb && \
    apt-get update && \
    apt-get install -y mysql-server && \
    rm -rf /var/lib/apt/lists/*

# Port exposé
EXPOSE 3306

# Lancer MySQL
CMD ["mysqld_safe"]
